import { PrismaClient, ContentItemType } from "../src/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
  connectionString: process.env.DATABASE_URL!,
});
const prisma = new PrismaClient({ adapter });

const GUIDES = [
  "Ayşe Nur Yılmaz",
  "Mehmet Can Demir",
  "Elif Sena Kara",
  "Ahmet Barış Öztürk",
] as const;

const DEMO_ITEMS = [
  {
    slug: "demo-5-dakika-nefes",
    title: "5 Dakika Nefes (Demo)",
    type: ContentItemType.AUDIO,
    durationSec: 300,
    goal: "Demo: Kısa nefes farkındalığı.",
    tags: ["DEMO", "nefes", "başlangıç"],
    guideName: GUIDES[0],
    forWho: "Yeni başlayanlar, gün ortası mola arayanlar.",
    forWhoNot: "Uzun meditasyon deneyimi olanlar.",
    previewUrl: "https://example.com/preview/nefes-demo.mp3",
    previewDurationSec: 75,
    fullUrl: "https://example.com/full/nefes-demo.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "demo-stres-azaltma",
    title: "Stres Azaltma Demo",
    type: ContentItemType.AUDIO,
    durationSec: 600,
    goal: "Demo: Stres ve gerginlik için kısa rehber.",
    tags: ["DEMO", "stres", "rahatlama"],
    guideName: GUIDES[1],
    forWho: "Stresli günler yaşayan herkes.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/stres-demo.mp3",
    previewDurationSec: 90,
    fullUrl: "https://example.com/full/stres-demo.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "demo-uyku-hazirlik",
    title: "Uykuya Hazırlık (Demo)",
    type: ContentItemType.AUDIO,
    durationSec: 900,
    goal: "Demo: Uyumadan önce zihni sakinleştirme.",
    tags: ["DEMO", "uyku", "rahatlama"],
    guideName: GUIDES[2],
    forWho: "Uykuya dalmakta zorlananlar.",
    forWhoNot: "Ağır uyku ilacı kullananlar.",
    previewUrl: "https://example.com/preview/uyku-demo.mp3",
    previewDurationSec: 60,
    fullUrl: "https://example.com/full/uyku-demo.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "sabah-uyanis-meditasyonu",
    title: "Sabah Uyanış Meditasyonu",
    type: ContentItemType.AUDIO,
    durationSec: 600,
    goal: "Güne bilinçli ve sakin başlamak.",
    tags: ["sabah", "uyanış", "farkındalık"],
    guideName: GUIDES[0],
    forWho: "Sabah rutini oluşturmak isteyenler.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/sabah.mp3",
    previewDurationSec: 80,
    fullUrl: "https://example.com/full/sabah.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "odaklanma-nefes",
    title: "Odaklanma Nefesi",
    type: ContentItemType.AUDIO,
    durationSec: 420,
    goal: "İş veya çalışma öncesi odak artırma.",
    tags: ["odak", "nefes", "iş"],
    guideName: GUIDES[1],
    forWho: "Dikkat dağınıklığı yaşayanlar.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/odak.mp3",
    previewDurationSec: 70,
    fullUrl: "https://example.com/full/odak.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "gece-rahatlama",
    title: "Gece Rahatlama",
    type: ContentItemType.AUDIO,
    durationSec: 720,
    goal: "Gün sonunda beden ve zihin rahatlatma.",
    tags: ["gece", "rahatlama", "uyku"],
    guideName: GUIDES[3],
    forWho: "Gün sonunda kapanmak isteyenler.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/gece.mp3",
    previewDurationSec: 65,
    fullUrl: "https://example.com/full/gece.mp3",
    previewText: null,
    fullText: null,
  },
  {
    slug: "tanitim-video-nefes",
    title: "Nefes Teknikleri Tanıtım",
    type: ContentItemType.VIDEO,
    durationSec: 600,
    goal: "Temel nefes tekniklerine giriş.",
    tags: ["video", "nefes", "tanıtım"],
    guideName: GUIDES[0],
    forWho: "Nefes çalışmasına yeni başlayanlar.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/nefes-video.mp4",
    previewDurationSec: 90,
    fullUrl: "https://example.com/full/nefes-video.mp4",
    previewText: null,
    fullText: null,
  },
  {
    slug: "vucut-tarama-rehberi",
    title: "Vücut Tarama Rehberi",
    type: ContentItemType.VIDEO,
    durationSec: 900,
    goal: "Bedensel farkındalık için rehberli tarama.",
    tags: ["vücut tarama", "farkındalık", "video"],
    guideName: GUIDES[2],
    forWho: "Beden farkındalığı geliştirmek isteyenler.",
    forWhoNot: "Ciddi bedensel ağrı yaşayanlar (önce doktora danışın).",
    previewUrl: "https://example.com/preview/tarama.mp4",
    previewDurationSec: 75,
    fullUrl: "https://example.com/full/tarama.mp4",
    previewText: null,
    fullText: null,
  },
  {
    slug: "mindfulness-temeller",
    title: "Mindfulness Temelleri",
    type: ContentItemType.VIDEO,
    durationSec: 720,
    goal: "Mindfulness kavramı ve günlük uygulama.",
    tags: ["mindfulness", "temel", "video"],
    guideName: GUIDES[3],
    forWho: "Mindfulness ile yeni tanışanlar.",
    forWhoNot: null,
    previewUrl: "https://example.com/preview/mindfulness.mp4",
    previewDurationSec: 85,
    fullUrl: "https://example.com/full/mindfulness.mp4",
    previewText: null,
    fullText: null,
  },
  {
    slug: "meditasyon-nedir",
    title: "Meditasyon Nedir?",
    type: ContentItemType.TEXT,
    durationSec: 480,
    goal: "Meditasyonun tanımı ve türleri.",
    tags: ["okuma", "temel", "bilgi"],
    guideName: GUIDES[1],
    forWho: "Meditasyonu merak eden herkes.",
    forWhoNot: null,
    previewUrl: null,
    previewDurationSec: 60,
    fullUrl: null,
    previewText: "Meditasyon, dikkati kasıtlı olarak belirli bir nesneye yönlendirme pratiğidir. Bu yazıda temel kavramları bulacaksınız.",
    fullText:
      "Meditasyon binlerce yıldır uygulanan bir pratik olup, zihinsel berraklık ve duygusal dengeyi destekler. Bu metin demo amaçlı tam içeriktir. Üyelik ile tüm metinlere erişebilirsiniz.",
  },
  {
    slug: "nefes-turleri",
    title: "Nefes Türleri ve Etkileri",
    type: ContentItemType.TEXT,
    durationSec: 540,
    goal: "Farklı nefes tekniklerinin kısa özeti.",
    tags: ["nefes", "okuma", "teknik"],
    guideName: GUIDES[0],
    forWho: "Nefes çalışmasına ilgi duyanlar.",
    forWhoNot: null,
    previewUrl: null,
    previewDurationSec: 70,
    fullUrl: null,
    previewText: "Diyafram nefesi, kutu nefesi ve 4-7-8 tekniği gibi yaygın nefes türlerine bu yazıda yer veriyoruz.",
    fullText:
      "Diyafram nefesi karın bölgesinin nefesle genişlemesini içerir. Kutu nefesi eşit sürelerde nefes alıp vermeyi, 4-7-8 ise uyku ve sakinleşme için kullanılır. Bu metin demo tam metindir.",
  },
  {
    slug: "duygusal-denge",
    title: "Duygusal Denge İçin İpuçları",
    type: ContentItemType.TEXT,
    durationSec: 600,
    goal: "Günlük hayatta duygusal dengeyi destekleyen pratikler.",
    tags: ["duygu", "denge", "ipucu"],
    guideName: GUIDES[2],
    forWho: "Duygusal dalgalanmalar yaşayanlar.",
    forWhoNot: null,
    previewUrl: null,
    previewDurationSec: 65,
    fullUrl: null,
    previewText: "Duyguları bastırmak yerine fark etmek ve kabul etmek, uzun vadede dengeyi kolaylaştırır.",
    fullText:
      "Duygusal denge için düzenli nefes pratiği, beden taraması ve günlük kısa meditasyon önerilir. Bu demo metin tam içerik örneğidir.",
  },
];

async function main() {
  for (const item of DEMO_ITEMS) {
    await prisma.contentItem.upsert({
      where: { slug: item.slug },
      create: {
        ...item,
        isPreviewAvailable: true,
        isPublished: true,
      },
      update: {
        title: item.title,
        type: item.type,
        durationSec: item.durationSec,
        goal: item.goal,
        tags: item.tags,
        guideName: item.guideName,
        forWho: item.forWho,
        forWhoNot: item.forWhoNot,
        previewUrl: item.previewUrl,
        previewDurationSec: item.previewDurationSec,
        fullUrl: item.fullUrl,
        previewText: item.previewText,
        fullText: item.fullText,
        isPreviewAvailable: true,
        isPublished: true,
      },
    });
  }
  console.log(`Seeded ${DEMO_ITEMS.length} content items.`);
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
