export const tr = {
  common: {
    search: "Ara",
    loadMore: "Daha Fazla",
    save: "Kaydet",
    cancel: "İptal",
    delete: "Kaldır",
    edit: "Düzenle",
    publish: "Yayınla",
    draft: "Taslak",
    close: "Kapat",
    back: "Geri",
    next: "İleri",
    previous: "Önceki",
    seeAll: "Tümünü Gör",
    readMore: "Devamını Oku",
    learnMore: "Daha Fazla Bilgi",
    startNow: "Şimdi Başla",
    free: "Ücretsiz",
    new: "Yeni",
    popular: "Popüler",
    featured: "Öne Çıkan",
    loading: "Yükleniyor...",
    noResults: "Sonuç bulunamadı",
    error: "Bir hata oluştu",
  },
  auth: {
    login: "Giriş Yap",
    register: "Kayıt Ol",
    logout: "Çıkış Yap",
    forgotPassword: "Şifremi Unuttum",
    resetPassword: "Şifre Sıfırla",
    email: "E-posta Adresi",
    password: "Şifre",
    confirmPassword: "Şifre Tekrar",
    name: "Adınız",
    welcomeBack: "Tekrar hoşgeldiniz",
    createAccount: "Hesap oluşturun",
    orContinueWith: "veya şu şekilde devam edin",
    alreadyHaveAccount: "Zaten hesabınız var mı?",
    dontHaveAccount: "Hesabınız yok mu?",
  },
  landing: {
    heroTitle: "Ruhunuzun Yolculuğuna Başlayın",
    heroSubtitle:
      "Meditasyon, yoga ve ruhsal gelişim için uzman rehberlerimizle tanışın. İç huzurunuzu birlikte keşfedelim.",
    heroCta: "Uzman Bul",
    heroCtaSecondary: "Ücretsiz Başla",
    videoTitle: "İlham Veren İçerikler",
    videoSubtitle: "Uzmanlarımızın sizin için hazırladığı özel videolar",
    categoriesTitle: "Keşfet",
    categoriesSubtitle: "Ruhsal yolculuğunuzda size rehberlik edecek alanlar",
    expertsTitle: "Uzman Rehberlerimiz",
    expertsSubtitle: "Alanında deneyimli, güvenilir rehberlerle tanışın",
    articlesTitle: "Son Yazılar",
    articlesSubtitle: "Ruhsal gelişim yolculuğunuza ilham katacak yazılar",
    coursesTitle: "Öne Çıkan Kurslar",
    coursesSubtitle: "Adım adım ilerleyebileceğiniz kapsamlı eğitimler",
    testimonialsTitle: "Yol Arkadaşlarımız Ne Diyor?",
    subscriptionTitle: "Ruhsal Dönüşümünüze Bugün Başlayın",
    subscriptionSubtitle:
      "Sınırsız içerik erişimi, uzman danışmanlığı ve daha fazlası",
    subscriptionCta: "Planları Keşfedin",
    newsletterTitle: "Haftalık İlham",
    newsletterSubtitle:
      "Her hafta ruhunuza iyi gelecek içerikler e-posta kutunuzda",
    newsletterPlaceholder: "E-posta adresiniz",
    newsletterCta: "Abone Ol",
  },
  chatbot: {
    greeting:
      "Merhaba, hoşgeldiniz. Bugün kendinizi nasıl hissediyorsunuz? İç dünyanızda neler oluyor?",
    placeholder: "İçinizdeki duyguları paylaşabilirsiniz...",
    send: "Gönder",
    thinking: "Düşünüyorum...",
    expertRecommendation: "Sizin için önerdiğim uzmanlar:",
    viewProfile: "Profili Gör",
    newChat: "Yeni Sohbet",
    title: "Ruhsal Rehberiniz",
  },
  experts: {
    title: "Uzmanlar",
    filterByCategory: "Kategoriye Göre",
    filterBySpecialty: "Uzmanlığa Göre",
    about: "Hakkında",
    articles: "Makaleler",
    courses: "Kurslar",
    reviews: "Yorumlar",
    experience: "yıl deneyim",
    verified: "Doğrulanmış Uzman",
  },
  articles: {
    title: "Makaleler",
    readTime: "dk okuma",
    by: "Yazan:",
    publishedAt: "Yayınlanma:",
    relatedArticles: "İlgili Yazılar",
  },
  courses: {
    title: "Kurslar",
    lessons: "Ders",
    enrolled: "kişi katıldı",
    enroll: "Kursa Katıl",
    startCourse: "Kursa Başla",
    continueCourse: "Kursa Devam Et",
    curriculum: "Ders İçerikleri",
    level: {
      beginner: "Başlangıç",
      intermediate: "Orta",
      advanced: "İleri",
    },
    completed: "Tamamlandı",
    inProgress: "Devam Ediyor",
  },
  subscription: {
    title: "Yolculuk Planları",
    subtitle: "Size en uygun planı seçin ve ruhsal dönüşümünüze başlayın",
    perMonth: "/ ay",
    currentPlan: "Mevcut Plan",
    selectPlan: "Bu Planı Seç",
    mostPopular: "En Popüler",
  },
  comments: {
    title: "Yorumlar",
    writeComment: "Deneyiminizi paylaşın...",
    submit: "Yorumu Gönder",
    reply: "Yanıt Ver",
    expertReply: "Uzman Yanıtı",
    noComments: "Henüz yorum yapılmamış. İlk yorumu siz yapın!",
  },
  footer: {
    platform: "Platform",
    categories: "Kategoriler",
    legal: "Yasal",
    about: "Hakkımızda",
    contact: "İletişim",
    privacy: "Gizlilik Politikası",
    terms: "Kullanım Şartları",
    faq: "Sıkça Sorulan Sorular",
    rights: "Tüm hakları saklıdır.",
  },
} as const;
